---
title: "location_monitors"
author: "Mazama Science"
date: "11/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)

coordinates <- c(lon = -122.032718, lat = 36.965317) # sante cruz ish
tlim <- c(20191021, 20191024) 
radius <- 20

```

```{r logging, echo=FALSE}
# Set up logging
MazamaCoreUtils::logger.setup()
MazamaCoreUtils::logger.setLevel("DEBUG")
```

```{r monitor_load, echo=FALSE}
monitors_within <- 
  PWFSLSmoke::monitor_load(startdate = tlim[1], enddate = tlim[2]) %>% 
  PWFSLSmoke::monitor_subsetByDistance(
    longitude = coordinates[1], 
    latitude = coordinates[2], 
    radius = radius
  )

monitor_col <- PWFSLSmoke::monitor_collapse(monitors_within, monitorID = 'Combined')
```

### Monitor Map
```{r monitor_map, echo=FALSE}
PWFSLSmoke::monitor_leaflet(monitors_within, ) %>%
  leaflet::addMarkers(lng  = coordinates[1], lat = coordinates[2]) %>% 
  leaflet::addCircles( lng = coordinates[1], 
                       lat = coordinates[2], 
                       radius = radius * 1000, 
                       fillOpacity = 0 )
```

### Monitor Data 
```{r monitor_plot, echo=FALSE, fig.height=6,warning=FALSE}
AirMonitorPlots::ggplot_pm25Timeseries( monitors_within,
                                        startdate = tlim[1], 
                                        enddate = tlim[2]-1 ) +
  ggplot2::geom_point(mapping = ggplot2::aes_(color = ~monitorID))  + 
  ggplot2::geom_path(mapping = ggplot2::aes_(color = ~monitorID)) + 
  ggplot2::geom_path( data = monitor_col$data,
                      mapping = ggplot2::aes_(x = ~datetime, y = ~Combined), 
                      linetype = 1, 
                      size = 2, 
                      color = 'grey52', 
                      alpha = 0.75 ) + 
  ggplot2::theme(legend.position = 'bottom') + 
  ggplot2::guides(color = ggplot2::guide_legend(ncol = 3))
```

### View Monitors
`r paste0('[Monitor: ',monitors_within$meta$monitorID , ']', '(', 'https://tools.airfire.org/monitoring/v4/#!/?monitors=', monitors_within$meta$monitorID, ')')`


