---
title: "Raster Package greatness"
output: html_notebook
---
# Demonstrate native NetCDF support in raster package
```{r}
library(raster)
library(rasterVis)

# Get Spatial polygon data
us <- raster::getData(country = 'USA', level = 1)
ca <- us[us$NAME_1 == 'California',]

# Read NetCDF
rasterBrick <- brick('~/Data/BlueSky/CANSAC-4km_2019103100_V2.nc')

# Define Color breaks
breaks <- c(1, 12, 35, 55, 150, 250, 350, 500)

# Crop the rasters to CA bbox
ca_rasterBrick <- crop(rasterBrick, ca)

# Plot
levelplot(ca_rasterBrick[[5:10]], at = breaks) + 
  layer(sp.lines(ca, col = 'darkgrey'))

```

# Monitor -> Grid
```{r}
library(PWFSLSmoke)
library(AirFireModeling)
ca_monitors <- monitor_load(20191031, 20191102) %>% monitor_subset(stateCodes = 'CA')
monitor_leaflet(ca_monitors)
```

```{r}
monitor_toRaster <- function( 
  ws_monitor, 
  res, 
  crs = '+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0', 
  extent = NULL, 
  from = NULL
) { 
  
    roundCell <- function(x, r) ceiling(x*(1/r))/(1/r)
    M <- data.frame( x = roundCell(ws_monitor$meta$longitude, res), 
                     y = roundCell(ws_monitor$meta$latitude, res), 
                     z = t(ws_monitor$data)[-1,] ) 
    ras <- rasterFromXYZ(M)
    
    #tm <- strftime(ws_monitor$data$datetime, '%Y-%m-%d %H:%M', tz = 'UTC')
    #names(ras) <- tm
    if ( !is.null(crs) ) crs(ras) <- crs
    if ( !is.null(extent) ) extent(ras) <- extent
      
    if ( !is.null(from) ) {
      ras <- projectRaster(from = ras, to = from)
    }
    return(ras)
  }
```

```{r}

ca_raster <- monitor_toRaster(ca_monitors, 0.5, extent = extent(rasterBrick))

levelplot(ca_raster[[1:12]])
```

```{r}
library(ggplot2)
library(gganimate)
gg_ca <- map_data('state')
gg <- gplot(ca_raster) + geom_raster(aes(fill = value), interpolate = T) + transition_states(variable)
gg
```

```{r}
us_monitors <- monitor_load(20191031, 20191102)
us_raster <- monitor_toRaster(us_monitors, 1)
gplot(us_raster[[1]]) + geom_raster(aes(fill = value))
```

```{r}

library(magrittr)
ca_monitors <- monitor_load(20191031, 20191103) %>% monitor_subset(stateCodes = 'CA')
cansac_raster <- brick('~/Data/BlueSky/CANSAC-4km_2019103100_V2.nc')
ca_raster <- monitor_toRaster(ca_monitors, res = 0.1)

corr <- raster::corLocal(ca_raster[[2]], ca_raster[[1]])
```

```{r}
plot(ca_raster[[12]])
```

```{r}
plot(cansac_raster[[12]])
```

```{r}
test <- monitor_toRaster(ca_monitors, res = 1, from = cansac_raster)
plot(test[[14]])
```
```{r}
plot(ca)
```

```{r}
cc <- corLocal(test[[12]], cansac_raster[[12]])
plot(cc) 

```

